### ISSUE TITLE
Bug in log file generator

### ISSUE THREAD

**Issue by zzz77** [PerfDotNet/BenchmarkDotNet#111]
In generated log file there is summary section which can contain incorrect formatted float values.
See attached screenshot (method MySort)
![bug](https://cloud.githubusercontent.com/assets/3635408/13581488/2ed6b840-e4b8-11e5-8721-de522d82d242.PNG)

**Comment by AndreyAkinshin** [comment]
It looks good to me. In the summary table, we use `,` as a separator because it improves readability.

**Comment by zzz77** [comment]
Oh. I just was confused by the fact that two similar benchmarks use different accuracy. And `,` used as a separator in the summary of first benchmark and `.` used as a separator in the another one. Seems strange.

**Comment by redknightlois** [comment]
@zzz77 The issue is at the generation of the summary report. 

@AndreyAkinshin If you look, the actual values are different. Sounds like a culture mixup somewhere in the ```.ToString()``` code

**Comment by AndreyAkinshin** [comment]
@zzz77, what do you suggest to use as a separator?
@redknightlois, don't see any difference in the values. We use different formatters and precision in statistics and summary by design.

**Comment by redknightlois** [comment]
@AndreyAkinshin You are right, the first has a different metric unit (micro-seconds instead of nano-seconds).

**Comment by AndreyAkinshin** [comment]
@redknightlois, yes, it's because of the value scope. `us` is the best time unit for the `MySort` statistics. But in the summary table, the best time unit is `ns` (we have another result with median = `483ns`).

**Comment by zzz77** [comment]
Oops. Sorry. I've just realized that. My bad.

**Comment by ppanyukov** [comment]
@zzz77 and @redknightlois, the difference in units is by design to accommodate varying magnitudes of stddev and things like that in different benchmarks. The separator is for readability. 

In the attached screenshot in the original post the `stddev` for `StandardSort` is so small that if we used `us` as units we wouldn't see it at all. Hence we use `ns`. And in order to compare results easily across benchmarks we therefore use `ns` everywhere for `stddev`. I hope this makes sense.

For background and the actual discussions please see https://github.com/PerfDotNet/BenchmarkDotNet/issues/16
