### ISSUE TITLE
[Proposal] remove jitting calls from BenchmarkProgram.txt

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#184]
The `Templates\BenchmarkProgram.txt` file contains the following lines:
```cs
				$ParamsContent$
				instance.setupAction();
				instance.targetAction();
```
The last two should be removed as jitting is expected to be performed by  `new MethodInvoker().Invoke()` call:
```cs
        public void Invoke(IJob job, long operationsPerInvoke, ...)
        {
            // Jitting
            setupAction();
            targetAction();
            idleAction();

            // Run
            ...
        }
```

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, we should run jitting as soon as possible. We can't remove these two lines from `BenchmarkProgram.txt` because it can spoil some benchmarks. E.g., it is important to run jitting for the target method _before_ the first use of the Stopwatch (See also: http://aakinshin.net/en/blog/dotnet/legacyjitx86-and-first-method-call/). Perhaps, we can remove the jitting section from the `Invoke` method.

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin
 wouldn't it be better to create explicit `Init()` step and to move all init logic (setting properties, performing the jitting calls etc) into it?

 I've naive-but-working implementation in `RunnableBenchmark` [here](https://github.com/rsdn/CodeJam/tree/master/BenchmarkDotNet/src/%5BL1_InProcess%5D/Toolchains).
Of course the API is just a mockup. For example, it should provide a way to notify diagnosers, but that's subject for another issue, #177.

**Comment by AndreyAkinshin** [comment]
I will think about it.

**Comment by AndreyAkinshin** [comment]
I have decided not to introduce an additional `Init()` method, jitting is too tricky, we could have some troubles with additional invocation. In the generated program, it is very important to jit our method as soon as possible.
