### ISSUE TITLE
Control over diagnoser for fine grained diagnosis

### ISSUE THREAD

**Issue by danielmarbach** [PerfDotNet/BenchmarkDotNet#217]
I was trying to measure an allocation problem with Task.ContinueWith see here

https://gist.github.com/mattwarren/7227890bf6fc76cf050231511089d6da#gistcomment-1812757

The code

```
            for (int i = 0; i < NumberOfTasks; i++)
            {
                var runningTask = Task.Delay(1);
                tasks.TryAdd(runningTask, runningTask);
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
                runningTask.ContinueWith(t =>
                {
                    Task toBeRemoved;
                    tasks.TryRemove(t, out toBeRemoved);
                }, TaskContinuationOptions.ExecuteSynchronously);
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            }

            return Task.WhenAll(tasks.Values);
```

I'm actually only interested in measuring the allocations for

```
                runningTask.ContinueWith(t =>
                {
                    Task toBeRemoved;
                    tasks.TryRemove(t, out toBeRemoved);
                }, TaskContinuationOptions.ExecuteSynchronously);
```

So what if a benchmark could be written like that

```
public void SomeBenchmark(Func<IDisposable> scope) 
{
                ... // like before
                using(scope()) {
                   runningTask.ContinueWith(t =>
                   {
                       Task toBeRemoved;
                       tasks.TryRemove(t, out toBeRemoved);
                   }, TaskContinuationOptions.ExecuteSynchronously);
                }
                ... // like before
}
```

This would basically tell the diagnoser to listen to ETW for the lifetime of the scope and then unhook again when the scope is disposed and so on.

Thoughts?

**Comment by adamsitnik** [comment]
> This would basically tell the diagnoser to listen to ETW for the lifetime of the scope and then unhook again when the scope is disposed and so on.

Currently this is not possible / supported. As far as I know we attach to the diagosed process at the begining of it's lifetime, and collect ETW events for it's whole lifetime (wamup & target).

My idea for the benchmark is following;

```cs
public class ContinueWithBenchmarks
{
	private object willRequireClosure = new object();

	[Benchmark(Baseline = true)]
	public Task ContinueWith()
	{
		return Task.CompletedTask
			.ContinueWith(
				(_, state) =>
				{
					GC.KeepAlive(state);
				}, willRequireClosure);
	}

	[Benchmark]
	public Task ContinueWithClosure()
	{
		return Task.CompletedTask
			.ContinueWith(
				_ =>
				{
					GC.KeepAlive(willRequireClosure);
				});
	}
}
```

Comments: 

- I allocate willRequireClosure once to not include this allocation in the cost of the benchmark.
- I use Task.CompletedTask for the same reason as above
- I use GC.KeepAlive to prevent any optimizations from removing the call
- I don't (a)wait the result Task because you just wanted to measure the cost of the closure allocation

The results I got:


BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4700MQ CPU 2.40GHz, ProcessorCount=8
Frequency=2338337 ticks, Resolution=427.6544 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0

Runtime=Core  Platform=X64  Jit=RyuJit  

              Method |      Median |     StdDev |         Max |         Min | Scaled |    Delta |  Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
-------------------- |------------ |----------- |------------ |------------ |------- |--------- |------- |------ |------ |------------------- |
        ContinueWith | 751.0828 ns | 17.1531 ns | 780.3814 ns | 726.3863 ns |   1.00 | Baseline |  90,00 | 18,00 |     - |              50,95 |
 ContinueWithClosure | 789.1133 ns | 20.6497 ns | 847.5842 ns | 767.6649 ns |   1.05 |     5.1% | 212,38 | 17,62 |     - |              74,50 |


I thinkt that it would be good to invite @mattwarren and @goldshtn to this discussion

**Comment by danielmarbach** [comment]
Thanks for the ideas! 

Regarding my initial idea, would that be an implemenation detail? Meaning since we cannot subscribe and unsubscribe ny proposal would the just drop or collect the ETW data?

**Comment by adamsitnik** [comment]
> Regarding my initial idea, would that be an implemenation detail? Meaning since we cannot subscribe and unsubscribe ny proposal would the just drop or collect the ETW data?

@danielmarbach I am sorry, but I don't understand your question. Could you explain it?

[This thread](https://github.com/PerfDotNet/BenchmarkDotNet/issues/200) has some good comments that explain how it is implemented and why.

**Comment by danielmarbach** [comment]
@adamsitnik let me illustrate what I meant

```
public void SomeBenchmark(Func<IDisposable> scope) 
{
                // here we listen to ETW events but drop all data
                using(scope()) {
                   // here we listen to ETW and collect the data
                }
                // here we listen to ETW events but drop all data
}
```

So the `Func<IDisposable>` would be a callback which hooks into the diagnosers, clearer?

**Comment by adamsitnik** [comment]
@danielmarbach First of all excuse me for very late response. I get your idea. The problem is that our current implementation has some limitations described [here](https://github.com/PerfDotNet/BenchmarkDotNet/issues/200). For example ETW fires new event when 100KB has been allocated, so if we attach and detach for each call we might omit some data. That's why we attach at the begining and detach at the end of benchmark runs.

My advice would be to write benchmarks that do not allocate anything except what you want to measure more than once. BenchmarkDotNet creates single instance of benchmarked class (via call to parameterless ctor) and runs `[Setup]` method once (if present at all). This is why in my sample I have put the allocation of the object to the ctor and used Task.CompletedTas instead of creating new Task every time. 

@mattwarren am I right?

**Comment by danielmarbach** [comment]
I think we still don't understand us ;) My proposal was to be always attached but essential discard or not discard data. But I got your point as well. And with any proposal it is just an idea ;) happy to get it rejected...

**Comment by mattwarren** [comment]
@adamsitnik yes you're essentially right.

But it's more than that, when we get a ETW event representing a 100KB bucket of allocations, we only get told the type of the last object to be allocated, i.e. the one that took it over 100KB limit. We don't know anything about the types of the other objects within the 100KB.

So whilst it would be great to offer the level of detail that things like [DotMemoryUnit](https://blog.jetbrains.com/dotnet/2015/03/04/unit-testing-and-memory-profiling-can-they-be-combined/) offer, they work in a completely different way and so we can't get the same info.

In a scenario like this:

``` csharp
[Benchmark]
public void SomeBenchmark(Func<IDisposable> scope) 
{
    // here we listen to ETW events but drop all data
    using(scope()) {
        // here we listen to ETW and collect the data
    }
    // here we listen to ETW events but drop all data
}
```
we're unlikely to get any meaningful ETW events. If the code inside `using(scope()) {..}` allocated less than 100KB we'd get no events at all.

It's only because we collect events over a longer period of time, where there are 100's or 1000's of iterations of the `[Benchmark]` method that we can give any meaningful numbers.
