### ISSUE TITLE
.csv results output does not play well with Excel or Google Sheets

### ISSUE THREAD

**Issue by jackmott** [PerfDotNet/BenchmarkDotNet#241]
Both Excel and Google Sheets expect that .csv means comma delimited, and by default import the file improperly.

If it was named .txt, or actually made comma delimited, this would be resolved.

I'm happy to do a PR to implement either fix, if this fix or something like it is desired.

**Comment by adamsitnik** [comment]
Hi!

Sure, go ahead with the PR. The class responsible for export to csv [CsvExporter](https://github.com/PerfDotNet/BenchmarkDotNet/blob/c6405a91bee90de6a12aee24755fbb783c2d9052/BenchmarkDotNet/Exporters/CsvExporter.cs)

Thanks in advance,
Adam

**Comment by AndreyAkinshin** [comment]
@jackmott, Excel take the list delimiter from your regional settings. You can check this setting (`TextInfo.ListSeparator`) for different cultures with help of [CultureInfoExplorer](https://github.com/AndreyAkinshin/CultureInfoExplorer).

I like semicolon like a list separator instead of comma because comma can be also `NumberFormat.NumberDecimalSeparator`. In case of semicolon, you are sure that it is a list separator.

Anyway it is a good idea to have the separator as a parameter. It would be cool to add it as an argument to the `CsvExporter` constructor (with a default value) and [CsvExporterAttribute](https://github.com/PerfDotNet/BenchmarkDotNet/blob/3ab5784cdf54b6f2ea503ef94da537e5918bc12b/src/BenchmarkDotNet.Core/Attributes/Exporters/CsvExporterAttribute.cs).

**Comment by AndreyAkinshin** [comment]
Now we support RFC 4180:
* Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.
* Default separator will be chosen based on your `CurrentCulture`
* You can also specify separator manually (comma or semicolon)
