### ISSUE TITLE
Can not run in FSI?

### ISSUE THREAD

**Issue by rojepp** [PerfDotNet/BenchmarkDotNet#255]
Sorry if this is a stupid bug report, this is my first attempt at using this library. 

I have this class for benchmarking:
```fsharp
type MapComparison () =
    let mutable fsmap : Map<int64,int64> = Map.empty<_,_>
    let mutable hashmap = HashMap<int64,int64>()

    [<Params (100, 1000, 10000, 100000)>] 
    member val public DictSize = 0L with get, set

    [<Setup>]
    member self.SetupData() =
        for i in 0L .. self.DictSize do
           fsmap <- Map.add i i fsmap
           hashmap <- hashmap.Add(i,i )

    [<Benchmark>]
    member self.HashMapLookup () = 
      for i in 0L .. self.DictSize do
        let b = hashmap.Get i
        ()

    [<Benchmark>]
    member self.FSharpMapLookup () = 
      for i in 0L .. self.DictSize do
        let b = fsmap.[i]
        ()
BenchmarkDotNet.Running.BenchmarkRunner.Run<MapComparison>()
```

For each of the test sizes, I'll get this error: 
> // Validating benchmarks:
> // **************************
> // Benchmark: MapComparison_HashMapLookup__DictSize-100
> // *** Generate *** 
> // Result = Failure
> // Exception: The invoked member is not supported in a dynamic assembly.

Am I doing something I'm not supposed to? 
This is on Windows 10, 64-bit. All the code that is being tested is built in Release, but the code above is in an F# script which I send to interactive.

**Comment by adamsitnik** [comment]
Hello @rojepp !

I am afraid that this scenario is not supported. We will also rather not add such feature because we encourage our users to close all applications (including IDE) before running benchmarks, to reduce the chance for results corruption.

However we support classic F#, you can find sample project [here](https://github.com/PerfDotNet/BenchmarkDotNet/tree/master/samples/BenchmarkDotNet.Samples.FSharp). We also support F# on .NET Core, samples [here](https://github.com/PerfDotNet/BenchmarkDotNet/tree/master/samples/BenchmarkDotNet.Samples.FSharp.Core)

**Comment by rojepp** [comment]
Ok! Thanks for answering!
