### ISSUE TITLE
BenchmarkDotNet Out-of-box experience and "getting started" documentation

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#33]
I just wanted to put together a list of things that I *think* could be done to make it easier for new users to get started with BenchmarkDotNet.

- [X] *Getting started* guide on the github repo 
  - at the moment the front page mostly covers "*Why is microbenchmarking hard?*", which is really valuable, but I think it should be put elsewhere and linked to.
  - I think the first thing people should see is a list of features (there already), plus a really brief "*getting started*" guide, showing how to write a simple benchmark and how to run it (some of this already exists).
- [ ] Use NuGet to automatically add a simple benchmark to your project when you add the BenchmarkDotNet package. 
  - I've [done this before](https://github.com/minibench/minibench.warren/blob/master/NuGet-Package/content/SampleBenchmark.cs.pp) and NuGet makes it easy via [source code transformations](https://docs.nuget.org/Create/Configuration-File-and-Source-Code-Transformations)
- [ ] ????? (anything else)

Let me know if you have any other ideas and I'll add them to the list above, then we can tick them off as they get done.

**Comment by AndreyAkinshin** [comment]
“Getting started” is a great idea, we definitely should have such section.
We can replace "Why is microbenchmarking hard?" with the link to http://andreyakinshin.gitbooks.io/performancebookdotnet/content/science/microbenchmarking.html

**Comment by AndreyAkinshin** [comment]
@mattwarren, I have updated the [README](https://github.com/PerfDotNet/BenchmarkDotNet). What do you think?

**Comment by smudge202** [comment]
My thoughts on getting started (and apologies if I didn't follow the readme correctly:

![benchmarkdotnet](https://cloud.githubusercontent.com/assets/2247869/11009447/ecb2c9f2-84ce-11e5-804d-60e1941df9c9.PNG)

**Comment by mattwarren** [comment]
@smudge202 how exactly are you executing the tests?

From reading [this comment](https://github.com/clean-development/engine/issues/16#issuecomment-154550609) I assume that you are using DNX, is that right? 

@AndreyAkinshin has only recently [added support for CoreCLR](https://github.com/PerfDotNet/BenchmarkDotNet/pull/43#issuecomment-151664639), so maybe this is related

**Comment by AndreyAkinshin** [comment]
The CoreCLR support will be added after [Microsoft Connect(); 2015](http://connect2015.visualstudio.com/), I'm waiting for some updates. =)

**Comment by mattwarren** [comment]
Do you know if the issue that @smudge202 is getting is related to DNX/CoreCLR support?

Or do you think it's a general problem because his Benchmark look like this:

``` csharp
[Benchmark]
public void DispatchingToNoReceivers()
    => Dispatcher.Dispatch(Event);
```
and we don't currently support that type of Benchmark?

**Comment by smudge202** [comment]
As per the comment you referenced, @mattwarren , I'm fairly sure it'll be a DNX incompatibility. Unfortunately, the NuGet package doesn't list supported frameworks.

**Comment by mattwarren** [comment]
Ignore my comment above, I just ran a test and we do support `[Benchmark]` methods created with the new C# 6 syntax, i.e. this works fine:

``` csharp
[Benchmark]
public void SleepWithCSharp6Syntax() => Thread.Sleep(100);
```

**Comment by smudge202** [comment]
@mattwarren, I believe you're confusing DNX/CoreCLR with C#6. Two very different things.

C#6 is independent, simply something the compiler does or does not support.

**Comment by mattwarren** [comment]
@AndreyAkinshin I just saw this post [The road to DNX – part 1](http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html) and thought you might find it useful when you do the DNX/CoreCLR work.

**Comment by smudge202** [comment]
I've taken a look at this issue and published my WIP branch [here](https://github.com/smudge202/BenchmarkDotNet/tree/features/33-dnx-compatibility).

The actual issue is of course an incompatibility with vNext projects (or whatever name we're going by today), but I went a step further and converted the existing projects too (hopefully that doesn't present too much confusion, but it does prove that even the existing tests fail when hosted by DNX). I actually wanted to see if we could get a `netstandard1.*`/`dotnet5.*+1` TFM in there as well, but I think the third party and framework dependencies will prevent that.

Anyway, the specific issue is that whilst running under DNX (such as through the `xunit.runner.dnx` as shown in the linked fork because I've converted the existing tests to run under DNX), you don't get as much information or even the same information relating to assemblies. Assembly paths will typically return the location of `dnx.exe`, whilst `Assembly.Location` will return null, as is the case on [this line](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Toolchain/Classic/BenchmarkClassicGenerator.cs#L155).

To work around this, I previously used [this stackoverflow answer](http://stackoverflow.com/questions/33071696/how-to-get-executing-assembly-location). Here lies the issue, the current API handles all assembly/file/type handling internally and I see no obvious extensibility points whereby DNX could be plugged in to the core library allowing the location to be retrieved correctly based upon the underlying runtime.

I could take a stab at making BenchmarkDotNet more extensible in order to allow such a plugin mechanism, though it may well be easier to cross compile the core code with separate `BenchmarkClassicGenerator` classes based upon TFM and wrap them uptogether in the same nuget package? I don't want to sink too much time into this without someone up the chain taking a peak and pointing me in the direction you'd like to go (even if that direction is to buzz off :) )

**Comment by AndreyAkinshin** [comment]
@smudge202,
> I could take a stab at making BenchmarkDotNet more extensible in order to allow such a plugin mechanism

I'll be grateful for any help! CoreCLR support is a very important feature, we need it in order to measure efficiency of new version of RyuJIT.

About the architecture: now we have the following interfaces: `IBenchmarkGenerator`, `IBenchmarkBuilder`, `IBenchmarkExecutor`, and the "classic" implementations of it. I want a new "DNX" implementations (or which name should we choose?). Next, `BenchmarkToolchainFacade` should be able to create a facade for new implementation in the `CreateToolchain` method. The `BenchmarkToolchain` enum should have a new value (like Dnx) which we will use in `BenchmarkTask`s. Ideally, the DNX support shouldn't affect to other parts of the library (except Generator/Builder/Executor).

Feel free to ask any details (we can discuss the subject in a separate issue or in the chat).

**Comment by smudge202** [comment]
Thanks for the information, @AndreyAkinshin . To be clear, I believe CoreCLR support and DNX support are going to be two different issues.

To move to CoreCLR (and take advantage of what I hear is coming with `rc2` in February, I think we need to find a way to drop the dependencies on `System.Management`, `Microsoft.Diagnostic.Runtime`, `Dia2Lib`, and `Interop.Dia2Lib`. To be honest, apart from seeing that we reference them, I haven't see how deeply nested the dependency goes. I recommend opening a second issue to tackle CoreCLR.

With regards to DNX, I actually took a look at implementing a cross compiled version last night. I defined `DNX` (which I think David Fowler hates...) into a `dnx451` target, pulled in a `Microsoft.Dnx.Runtime` dependency for the dnx target, and started going through all the interfaces available through the common service locator. We can get access to the `LibraryManager`, `RuntimeEnvironment` and `ApplicationEnvironment`, however, none of those expose the assembly location. Thinking about it, that is probably by design. I won't speculate with regards to my very poor understanding on how DNX compiles (on the fly?) and how assembly location probably doesn't make sense.

I think there are two options. Ask guys from the DNX team (hop into their gitter or @ them on here) what they would recommend (should probably leave that as a last resort). Alternatively, examine why it is we need (or think we need) the assembly location. I only briefly glanced at the consumer code, but it almost looked like it was trying to generate a `csproj` style reference?

**Comment by AndreyAkinshin** [comment]
> I think we need to find a way to drop the dependencies on System.Management, Microsoft.Diagnostic.Runtime, Dia2Lib, and Interop.Dia2Lib

@mattwarren, can you move these dependencies from the core to another assembly in the nearest future?

**Comment by mattwarren** [comment]
> I think we need to find a way to drop the dependencies on System.Management, Microsoft.Diagnostic.Runtime, Dia2Lib, and Interop.Dia2Lib

Yeah no problem, in the next few days I'll check-in some changes so that these are moved out of BenchmarkDotNet core and put into "BenchmarkDotNet.Diagnostic" as we discussed.

**Comment by mattwarren** [comment]
In [The road to DNX - part 2](http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-2.html), Marc says this:

>  I do not recommend polluting all your code with constant #if. Rather, my strategy is to [create a utility class that bridges the gap](https://github.com/mgravell/fast-member/blob/master/FastMember/TypeHelpers.cs) (usually, but not always, via extension methods), and have just that class deal with different implementations.

It would be nice if we could follow this advice as it seems a lot cleaner to have all the `#if` code in as few places as possible. (not saying you **were** going to do this, just wanted flag it up)

**Comment by smudge202** [comment]
Yup. I usually `ifdef` to get things running and then look to clean things up. Happy to go with extensions if/when we move forward on this.

**Comment by AndreyAkinshin** [comment]
@mattwarren, are you happy with current version of README?

**Comment by mattwarren** [comment]
It's been a while since I read through it all the way, I'll take a look in the next day or so and if I spot anything I'll make some changes.

**Comment by AndreyAkinshin** [comment]
Great, thanks.

**Comment by AndreyAkinshin** [comment]
Now we have nice documentation with the "Getting started" section. We also have another issue about online documentation: https://github.com/PerfDotNet/BenchmarkDotNet/issues/219
