### ISSUE TITLE
Dependent assemblies are not copied or added to the project file.

### ISSUE THREAD

**Issue by redknightlois** [PerfDotNet/BenchmarkDotNet#49]
When benchmarking complex operations you may end up with situations like the following:

On assembly ```assembly1.dll```
```csharp
public class A
{}
```
On assembly ```benchmark.dll```
```csharp
public class Program : A
{
   [Benchmark]
   public void Method ()
   {
       // calling some method of A for initialization.  
   }
}
```
In this case ```benchmark.dll``` will be referenced while  ```assembly1.dll``` is not causing a build failure like the following:

```
// **************************
// Benchmark: Program_Method (Throughput_HostPlatform_HostJit_NET-HostFramework_ArraySize) [-w=5 -t=10]
// Generated project: G:\Src\ravendb-3.5-git\Raven.Voron\Voron.Tryout\bin\Release\Program_InsertInTable_Throughput_HostPlatform_HostJit_NET-HostFramework_ArraySize
// Build:
// Program.cs(14,18): error CS0012: The type 'Voron.Tests.Tables.TableStorageTest' is defined in an assembly that is not  referenced. You must add a reference to assembly 'Voron.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=37f41c7f99471593'.
// OverallResult = Failure
// ***** Competition: Finish  *****
```

**Comment by mattwarren** [comment]
thanks for the bug report.

Yeah I think the problem is that we don't look in enough places for what we need to reference. At the moment we only include the namespace/reference for the the return type of the `[Benchmark]` method and the containing class. See https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Toolchain/Classic/BenchmarkClassicGenerator.cs#L38-L45.

Looks like we'll have to dig a bit deeper and look into the contents of the `[Benchmark]` method.

@AndreyAkinshin I don't mind picking this one up?

**Comment by redknightlois** [comment]
Thanks, with that information I was able to workaround it returning a reference to this :)

**Comment by mattwarren** [comment]
> Thanks, with that information I was able to workaround it returning a reference to this :)

LOL, yeah that'll do it! I'll have a look and see if we can do something better here. 

It's not a great experience if BenchmarkDotNet produces code that won't compile!
