### ISSUE TITLE
Parallel.For in benchmark

### ISSUE THREAD

**Issue by inTagger** [PerfDotNet/BenchmarkDotNet#5]
When `Parallel.For()` is used in a benchmark, there is only 12% usage of 8x cores CPU by whole process, because of priority of the test thread which is set in `Prepare()` method: `Thread.CurrentThread.Priority = ThreadPriority.Highest`. Outside of a `Benchmark` `Parallel.For()` uses up to 100% of CPU on all cores.

**Comment by omariom** [comment]
Windows is known to be fairly good at scheduling. So at least on Windows and  by default the benchmark process should not be affinitized.  If there are other high priority threads - affinitized to the same core  or just happen to be scheduled on it -  the benchmark process will suffer because Windows won't schedule it on another free core.

**Comment by AndreyAkinshin** [comment]
It is interesting. @mattwarren, what do you think?

**Comment by mattwarren** [comment]
Sorry, I'm no expert on multi-threading and thread affinity. 

Maybe we can measure it, although I'm not sure what type of metrics we need to look for, is there such as thing as "Thread Scheduling Events"?

**Comment by omariom** [comment]
> Sorry, I'm no expert on multi-threading and thread affinity. 

Me neither )

We can try to run another process (or a few of them) with the same high priority.

**Comment by AndreyAkinshin** [comment]
In `v0.9.0`, the processor affinity is an optional property of each job.
