### ISSUE TITLE
0 ticks? Could be possible?

### ISSUE THREAD

**Issue by redknightlois** [PerfDotNet/BenchmarkDotNet#70]
There appers to be something odd in this benchmark, but I cannot figure out what it is.
https://gist.github.com/redknightlois/2874ea1ce7a8b75e1779

Maybe you can take a look and see something that I am missing.

**Comment by AndreyAkinshin** [comment]
Your code is just super-fast. I think, all of your structures is in the L1 cache after warmup. So, you try to measure several `mov` operations between different parts of L1. I call such benchmark “unmeasurable” (and I want to implement a special analyzer which will warn you about such situations).
Probably, you should try a real-world example of copying. E.g., copying one array of structs to another one. It suppresses the cache effect and benchmark will work with RAM instead of the cache.

**Comment by AndreyAkinshin** [comment]
I found a bug, will be fixed soon.

**Comment by AndreyAkinshin** [comment]
Fixed in `v0.9.1`.

**Comment by redknightlois** [comment]
So it was a bug. Glad to know. I will rerun those tests when I have a chance. Probably also add them to the samples, there are JIT ones.
