### ISSUE TITLE
Referenced assembly dll-file (directly via file) not referenced in generated Program.csproj

### ISSUE THREAD

**Issue by nietras** [PerfDotNet/BenchmarkDotNet#72]
Referencing a file directly (e.g. Browse... for reference) does not work, the generated Program.csproj does not reference it.

**Comment by nietras** [comment]
The code https://github.com/DotNetCross/Memory.Unsafe, which has a simple Benchmark test under src shows the issue. Since Program.csproj is not referencing the DotNetCross.Memory.Unsafe.dll it does not work.

**Comment by AndreyAkinshin** [comment]
Thanks for the bug report, we will fix it.

**Comment by mattwarren** [comment]
@nietras sorry for the delay in getting to this issue. I tried with the latest NuGet build (0.9.1) and this now works. We now have a fallback mechanism for building the benchmark which handles your scenario

```
BuildManager.DefaultBuildManager can't build this project. =(
Let's try to build it via BuildBenchmark.bat!
...
```

this shells out to MSBuild and you eventually get:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.55
// Result = Success
```

Full output:

![image](https://cloud.githubusercontent.com/assets/157298/13295265/f31911d2-db1f-11e5-9cb0-614d250c1880.png)

**Comment by mattwarren** [comment]
Although after thinking about this a bit more, I'm pretty sure that it only now works by coincidence not by design!

So we still need a proper fix

**Comment by adamsitnik** [comment]
Current implementation adds two references to .csproj:
```
$TargetAssemblyReference$
$TargetMethodReturnTypeAssemblyReference$
```

The only workaround for me for now would be to make one of these benchmark return some type from the referenced dll.

**Comment by mattwarren** [comment]
@adamsitnik @AndreyAkinshin I just wanted to get your opinion on the best way to solve this, as this issue has come up a few times now (also see #123)

I've had a look and the reason why MsBuild [works the 2nd time](https://github.com/PerfDotNet/BenchmarkDotNet/issues/72#issuecomment-188382135), is because when we shell out and call `BuildBenchmark.bat\ the [ResolveAssemblyReference Task](https://msdn.microsoft.com/en-us/library/9ad3f294.aspx) is able discover/resolve second and nth-order dependencies.

So one option is to work out how to do this when we run MSBuild the first time, i.e. when we run it directly from inside BenchmarkDotnNet. However this won't help with `dotnet` or `CoreCLR` as they don't use MSBuild.

So I think that the best approach is to analyse the `.csproj` file that the Benchmark is in and ensure that we include any dependencies from that in the `.csproj`/`project.json` file that we generate at runtime, does that sound sensible?

**Comment by adamsitnik** [comment]
Dotnet cli resolves the dependencies in recursive way, so we just add dependency to benchmark.Target.Type.Assembly and it resolves it correctly, so the bug affects only Classic toolchain.

I did some PoC and I think that we could use 'benchmark.Target.Type.Assembly.GetReferencedAssemblies()'. The problem is that it is really hard  to tell for 100% if certain assembly is some predefined System assembly like "mscorlib.dll" or "System.Core" or "WindowsBase" like in this particular case. Because if it is, then we should not set the hintPath.

The other problem are custom path's, but we can use assembly.Location to tell whether it is custom or not.

Or another idea: we can reference all dlls that are in the current directory.

What do you think?

**Comment by mattwarren** [comment]
> Dotnet cli resolves the dependencies in recursive way, so we just add dependency to benchmark.Target.Type.Assembly and it resolves it correctly, so the bug affects only Classic toolchain.

I didn't realise this. In that case maybe we can just get MSBuild to do the hard work for us via the  `ResolveAssemblyReference` Task? It's able to resolve all the dependencies when we try the 2nd time by shelling out and running `BuildBenchmark.bat. (Although I've just realised that this isn't solving the problem for #123?)

**Comment by adamsitnik** [comment]
@mattwarren Currently I cannot see a good solution.

I will try to write something based on 'benchmark.Target.Type.Assembly.GetReferencedAssemblies();' and come back to you with the results.

**Comment by adamsitnik** [comment]
@mattwarren I believe that I have found the cure, please take a look at #125
